#!/bin/bash

# Most of this is taken directly from datalad-htcondor. (Thanks!)

set -eu

sed -e 's,/debian ,/debian-devel ,g' /etc/apt/sources.list.d/neurodebian.sources.list | \
    grep -v data | \
    tee /etc/apt/sources.list.d/neurodebian-devel.sources.list
    # TODO(asmacdo) put these sudo s back
apt-get update

debconf-set-selections -v tools/ci/htcondor_dconf_selections
apt-get install -y htcondor

# Prevent htcondor from bind-mounting a scratch directory over /tmp and
# interfering with our test location. This is necessary as of htcondor v8.7.10
printf "\\nMOUNT_UNDER_SCRATCH = /var/tmp\\n" | \
    tee -a /etc/condor/condor_config

service condor start

# Try twice to give condor some time to fire up.
condor_status || (sleep 5; condor_status)
condor_run 'uname -a'  # perform a test submission
